name: build

on:
  push:
    branches: [ main, release ]
    paths-ignore:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - name: Publish to Docker
        run: |
          mvn -B spring-boot:build-image -Dspring-boot.build-image.publish=true \
          -Ddocker.username=${{ secrets.DOCKER_USER }} -Ddocker.password=${{ secrets.DOCKER_TOKEN }} \
          -DskipTests
