name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          #MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DB: impotgithubaction
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy
        run: |
          mvn -B spring-boot:build-image -Dspring-boot.build-image.publish=true \
              -Ddocker.user="${{ secrets.DOCKER_USER }}" \ 
              -Ddocker.token="${{ secrets.DOCKER_TOKEN }}" \
              -DskipTests